### ISSUE TITLE
labels genes and tf in Panda output

### ISSUE THREAD

**Issue by michelegentili93** [netZoo/netZooPy#189]
Hi,

I have run pandas on this data:
Gene expression initial shape:  (5217, 50)
Motif Shape:
 Tf       105
Gene    3551

I can't find the labels for the rows and columns of the output matrix `panda.panda_network`. I get:
panda.num_genes = 5088
panda.panda_network.shape  = (105, 5088)
panda.motif_matrix.shape = (105, 5088)
len(panda.motif_genes) = 3551
len(panda.expression_genes) = 5217

Which genes should I use for the columns of panda.panda_network? Thanks :)

**Comment by marouenbg** [comment]
Hey @michelegentili93 ,

Could you please copy the call to panda ?

**Comment by marouenbg** [comment]
also can you run np.unique on your gene expression genes and np.unique on your motif genes and tell me the length of result?

**Comment by michelegentili93** [comment]
thanks for the reply. Here is the call:
panda = Panda(expression_file='YeastCCData_Expression_rep1.txt' , motif_file='YeastCCData_Motif.txt', 
              ppi_file='Identity_PPI.csv')

n_unique motif Gene: 3551
len(set(panda.expression_genes)): 5088

Good call, I din't check if the gene expression had some duplicates...! So I guess I have to keep the same order in panda.expression_genes, but removing duplicates.

**Comment by marouenbg** [comment]
Hi @michelegentili93 , so PANDA by default takes the union set of expression genes and motif genes by adding rows of zeros to non-overlapping genes, you can set that modeProcess to 'intersection' and you will get a smaller network but it won't add rows of zeros to the initial matrix. 
I am adding rows and columns for the output, thanks for spotting this.

**Comment by marouenbg** [comment]
Michele you can go ahead and reinstall from devel to get the result with labels.

**Comment by michelegentili93** [comment]
Hi, so there's still a mismatch between panda.expression_genes and the actual gene. In the picture I show that the panda.expression is different from the actual expression, obtained from the input file and using the genes order in panda.expression_genes (picture)

I noticed this because I assumed that the numpy matrix in panda.panda_network  has panda.motif_tfs as index and panda.expression_genes as columns, am I wrong?

<img width="388" alt="image" src="https://user-images.githubusercontent.com/15063931/124997229-3f411980-e018-11eb-9982-bd0e3431cfe5.png">

**Comment by marouenbg** [comment]
Hi @michelegentili93 ,

Yes this is expected, because PANDA will either run in 'union' or 'intersection' mode (in modeProcess argument).
For example, when set to intersection, it will take the intersection of motif genes and gene expression genes, therefore, panda.expression will be restricted to those genes only (panda.gene_names).

For your second question, yes you can have a matrix in the way you described it by setting modeProcess to 'legacy'. 
Please keep sending questions, it really helps improve the package.

**Comment by marouenbg** [comment]
added gene expression labels in panda.expression in #192

**Comment by marouenbg** [comment]
Hi @michelegentili93 ,
Is this issue fully resolved?

**Comment by marouenbg** [comment]
Hi @michelegentili93 ,

I am closing this issue, please let me know if you have any further questions.

Best,
Marouen
