### ISSUE TITLE
Error in generating Lioness file (-q) with command line panda

### ISSUE THREAD

**Issue by laurenhsu1** [netZoo/netZooPy#209]
I am running Panda with normalized expression data and ppi/tf data downloaded from grand (tissues_ppi and tissues_motif). It appears to run without issues until the end on the lioness call, where it encounters an error that `export_panda_results` is not assigned:

```
step: 39, hamming: 0.0008884414281395395
Running panda took: 11017.05 seconds!
Saving PANDA network to data/panda_output/zm4_test_out.txt ...
  Elapsed time: 17.93 sec.
Loading input data ...
  Elapsed time: 0.00 sec.
Traceback (most recent call last):
  File "../netZooPy/netZooPy/panda/run_panda.py", line 85, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../netZooPy/netZooPy/panda/run_panda.py", line 80, in main
    lioness_obj = Lioness(panda_obj)
  File "/Users/laurenhsu/Documents/GitHub/netZooPy/netZooPy/lioness/lioness.py", line 94, in __init__
    self.export_panda_results = obj.export_panda_results
AttributeError: 'Panda' object has no attribute 'export_panda_results'
```

The initial command I used was:
```
python ../netZooPy/netZooPy/panda/run_panda.py -e data/expr/zm4_test.txt -m data/fromgrand/tissues_motif.txt -p data/fromgrand/tissues_ppi.txt -o data/panda_output/zm4_test_out.txt -q data/panda_output/zm4_test_outq.txt
```

The `-o` file does save properly. I’d like to run lioness on the panda output, but am not sure how to proceed since the -q option file wasn’t outputted and the error occurred on that step.

Thanks!

**Comment by marouenbg** [comment]
Thank you for reporting this @laurenhsu1, I fixed the issue in https://github.com/netZoo/netZooPy/pull/210
You can reinstall netZooPy from the devel branch and try again.

**Comment by laurenhsu1** [comment]
Thanks @marouenbg. I reinstalled from devel and tried again, but this time it got killed by zsh:
```
Running panda took: 10748.93 seconds!
zsh: killed     python ../netZooPy/netZooPy/panda/run_panda.py -e data/expr/zm4_test.txt -m  
```
I'm not sure why this is happening, but I think I will try running the methods in python directly in a notebook. Let me know if you have other suggestions that I should try!

**Comment by marouenbg** [comment]
Hi @laurenhsu1 ,
It seems that it is a memory issue. To solve the initial error you had in #210 , I set the `save_memory` argument to false. This is necessary to keep the metadata for the lioness step.
Yes, it would help to run the functions from the python interface directly to traceback the error. As a first step, try running lioness on 1 sample to see if the error persists.
Let me know !

**Comment by laurenhsu1** [comment]
Hi @marouenbg, so I ended up rerunning from command line on a reduced sample (40), and it doesn't run into the memory issue anymore, though I did encounter a different error in lioness:

```
Saving PANDA network to data/panda_output/zm4_test_small_out.txt ...
  Elapsed time: 74.13 sec.
Loading input data ...
  Elapsed time: 0.00 sec.
Traceback (most recent call last):
  File "../netZooPy/netZooPy/panda/run_panda.py", line 85, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../netZooPy/netZooPy/panda/run_panda.py", line 80, in main
    lioness_obj = Lioness(panda_obj)
  File "/Users/laurenhsu/Documents/GitHub/netZooPy/netZooPy/lioness/lioness.py", line 143, in __init__
    indDF = indDF.append(pd.DataFrame(self.total_lioness_network)).transpose()
AttributeError: 'Lioness' object has no attribute 'total_lioness_network'
```
Thanks for your help with this!

**Comment by marouenbg** [comment]
Hi @laurenhsu1 ,
I am not sure what is going on, but I am suspecting the expression file.
Could you please reinstall from devel again and copy the output of the analysis?

**Comment by violafanfani** [comment]
Hi @laurenhsu1 this issue should now be solved by the CLI call to panda. If something else occur, feel free to open a new issue!
