### ISSUE TITLE
lioness puma variable copy

### ISSUE THREAD

**Issue by marouenbg** [netZoo/netZooPy#216]
Hi @violafanfani ,

I believe the variable copy issue exists in PUMA as well,
https://github.com/netZoo/netZooPy/blob/master/netZooPy/lioness/lioness_for_puma.py#L59

**Comment by violafanfani** [comment]
You are right. I am gonna take a moment to refactor panda appropriately as this looks like an important issue

**Comment by marouenbg** [comment]
adressed in https://github.com/netZoo/netZooPy/pull/218
