### ISSUE TITLE
PUMA MiR issue

### ISSUE THREAD

**Issue by talkhanz** [netZoo/netZooPy#271]
currently, PUMA  mir argument requires a filepath but this should facilitate a pandas dataframe as well

**Comment by violafanfani** [comment]
I am fixing it such that it allows a list to be passed. The miR object is usually a list of strings, right @marouenbg?

**Comment by marouenbg** [comment]
the miR object is read from a file, we would like to have it as a pandas dataframe

**Comment by violafanfani** [comment]
I just need you to confirm that the miR object is a list and not a dataframe ( that’s how it is read now )

**Comment by marouenbg** [comment]
ok let's go for a list, can you please add in the function description how it should be read ?
thanks

**Comment by violafanfani** [comment]
This should now be working. The miR object can be passed as a list and I added a snippet on how it is read right now from file. Thanks for suggesting the improvement!

**Comment by marouenbg** [comment]
Ok thanks, @talkhanz I think you can update code with this after new version is released.
