### ISSUE TITLE
Lioness indices

### ISSUE THREAD

**Issue by marouenbg** [netZoo/netZooPy#277]
Feature request by @talkhanz to add an argument in lioness to produce a set of noncontinuous samples for example [4,5,10] as opposed to start and end arguments that produce all samples between start and end.

**Comment by violafanfani** [comment]
What should the background be here? All samples and then run lioness on 4,5,10 only? or should everything be computed on 4,5,10 only?

**Comment by marouenbg** [comment]
yes, All samples and then run lioness on 4,5,10 only

**Comment by violafanfani** [comment]
Fixing with PR #279

**Comment by talkhanz** [comment]
very cool. thanks @violafanfani

**Comment by violafanfani** [comment]
It was fixed with #281 in the end. For now it is on the devel branch, will soon merge to master.
