### ISSUE TITLE
save_tmp 

### ISSUE THREAD

**Issue by michelegentili93** [netZoo/netZooPy#285]
I noticed that the default value of  save_tmp is True, I'd suggest to have it False, or to place a os.makedirs('./tmp',exists_ok=True) so that it creates the folder ./tmp if it doesn't exists.

**Comment by violafanfani** [comment]
Ehi Michele! Reference the specific line in the code you refer to, otherwise I don't know where to change this.

**Comment by michelegentili93** [comment]
https://github.com/netZoo/netZooPy/blob/add9e66bfa875af7d2a38d6ecb32c6a12a1863a6/netZooPy/puma/puma.py#L204

**Comment by michelegentili93** [comment]
or you can change here to False as default value
https://github.com/netZoo/netZooPy/blob/add9e66bfa875af7d2a38d6ecb32c6a12a1863a6/netZooPy/puma/puma.py#L88

**Comment by violafanfani** [comment]
Ok, should be fixed now. I changed it both for PUMA and PANDA.
