### ISSUE TITLE
panda --save_memory outputs the adjacency but without gene names

### ISSUE THREAD

**Issue by pmandros** [netZoo/netZooPy#289]
When using --save_memory the output is an adjacency matrix but without index and column names (i.e., without the gene names).

**Comment by violafanfani** [comment]
The save_memory flag is actually removing objects to free memory, and I agree that linking it to the output format is confusing. I began the transition towards the separation of the save_memory flag and the save_adjacency. For retrocompatibility reasons I am keeping the save_memory flag for now, with a warning that explains that it will get deprecated. From now, the correct way of saving an adjacency matrix with tf and gene names is the flag --as_adjacency.
