### ISSUE TITLE
-save_memory not very informative as a flag

### ISSUE THREAD

**Issue by pmandros** [netZoo/netZooPy#291]
-save_memory returns the adjacency matrix instead of the full edge list. So it saves space on your disk, but not memory. Wouldn't it be more constructive to rename this flag to --output_adj_matrix ?

**Comment by violafanfani** [comment]
Changing the flag name might be an issue for compatibility reasons, but we can use a different flag to save the full table instead of edge-list

**Comment by pmandros** [comment]
You are right. Thank you so much for the quick reply and for maintaining such an excellent repository!

**Comment by marouenbg** [comment]
![giphy](https://user-images.githubusercontent.com/7914548/204665071-9095603b-736e-4964-8cbf-5b682debf26a.gif)

**Comment by violafanfani** [comment]
Ok, I began the transition towards the separation of the save_memory flag and the save_adjacency. For retrocompatibility reasons I am keeping the save_memory flag for now, with a warning that explains that it will get deprecated. From now, the correct way of saving an adjacency matrix with tf and gene names is the flag `--as_adjacency`. This was added in #292

**Comment by marouenbg** [comment]
Hey @violafanfani ,
I don't think there is a need for a save_adjacency, both format (edge and adjacency) are accessible through the PANDA object. save_memory saves RAM memory by removing intermediate variable but does not change network format.
