### ISSUE TITLE
no --with-header option in PANDA

### ISSUE THREAD

**Issue by pmandros** [netZoo/netZooPy#294]
Hello, I though PANDA would have a --with-header option to be able to import expression with header (sample names). This feature would be great. Thank you!

**Comment by marouenbg** [comment]
Yes it has this argument https://github.com/netZoo/netZooPy/blob/master/netZooPy/panda/panda.py#L116

**Comment by pmandros** [comment]
It would be nice if it was accessible as a command line argument
