### ISSUE TITLE
Legacy mode without remove_missing=True causes shape mismatch

### ISSUE THREAD

**Issue by blawney** [netZoo/netZooPy#303]
There is a missing `[commind2]` index/subset at https://github.com/netZoo/netZooPy/blob/master/netZooPy/panda/panda.py#L522

This bug is triggered if you invoke the `Panda` constructor with `modeProcess='legacy'`, and keep the default value of `remove_missing=False`

**Comment by violafanfani** [comment]
This should be now fixed with the Franklin (v0.9.15) release
