### ISSUE TITLE
Unable to find hdf5 when building locally (Mac M1)

### ISSUE THREAD

**Issue by katehoffshutta** [netZoo/netZooPy#308]
When attempting to build netZooPy with local changes by running `pip install -e .` from the root directory of the repository, I get the following error:

```
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.
```

The error persists after reinstalling hdf5 with homebrew and setting the `HDF5_DIR` environment variable as the error message suggested.  This is happening on a Mac with M1 chip running Monterey 12.6.3.

**Comment by violafanfani** [comment]
Hi! This seems to be an M1-related issue. See [here for a workaround](https://stackoverflow.com/questions/73029883/could-not-find-hdf5-installation-for-pytables-on-m1-mac) and [here for the official documentation](https://www.pytables.org/usersguide/installation.html). 

An easy workaround is to use a conda environment where you can manually install pytables before running installing the package. For instance you can create a new environment and install pytables as follows:
```
conda create -n myenv python>3.7
conda install -c conda-forge pytables
pip install -e .
```

**Comment by violafanfani** [comment]
Great! I will add this to the discussions for future reference.
