### ISSUE TITLE
Lioness for dragon merge_col

### ISSUE THREAD

**Issue by violafanfani** [netZoo/netZooPy#322]
I am trying to run Lioness Dragon and I am encountering an issue with the merge column.
Shouldn't the renaming be based on the ext2 here?

https://github.com/netZoo/netZooPy/blob/98a46ce0682fbfa35894190f690fb28a47379736/netZooPy/lioness/lioness_for_dragon.py#L90C35-L90C35

@katehoffshutta

**Comment by katehoffshutta** [comment]
@violafanfani Yes, good catch. I will fix and submit a PR now!

**Comment by violafanfani** [comment]
Solved with PR #323
