### ISSUE TITLE
Initialization of protein-protein interaction in Panda

### ISSUE THREAD

**Issue by janursa** [netZoo/netZooPy#333]
I noticed in [this line of code](https://github.com/netZoo/netZooPy/blob/39df60c3dd305e425b90df10efb2ba264d57f389/netZooPy/panda/panda.py#L548), a value of 1 is assigned to the self-interaction of proteins. I am concerned about the implications of this assignment on the normalization of PPI values. In my dataset, the PPI values are relatively small, and this assignment of 1 to self-interactions prior to normalization could render these values negligible. Is this assignment a necessary step before normalization, or should there be a specific format for the PPI values to address this issue?

**Comment by marouenbg** [comment]
Feel free to repoen @janursa if you have other questions.
