### ISSUE TITLE
LIONESS Py error 

### ISSUE THREAD

**Issue by wilsonavac** [netZoo/netZooPy#335]
I am running lioness with cli like this: 

`netzoopy lioness -e /home/ubuntu/partial_expression.tsv -m /home/ubuntu/whole_blood_tissues_motif.txt -p /home/ubuntu/whole_blood_tissues_ppi.txt -op /home/ubuntu/copdgene_yes_cp_dev_panda_lion.txt -ol /home/ubuntu/yes_copd_dev_lion/ --computing gpu --panda_start 1 --panda_end 5 --precision single --save_memory --mode_process intersection --save_single_lioness --ignore_final`

And I am getting this error: 

 File "/opt/conda/lib/python3.10/site-packages/netZooPy/lioness/lioness.py", line 135, in __init__
    self.export_panda_results = obj.export_panda_results
AttributeError: 'Panda' object has no attribute 'export_panda_results'. Did you mean: 'save_panda_results'?

can you please help me :)

**Comment by violafanfani** [comment]
Hi @wilsonavac! This is the issue with `--save_memory` that doesn't keep the data from PANDA, hence the error in lioness. Try running it without the `save memory` flag, it should work. I will work on a fix, this should not be happening/ you shouldn't have access to that flag. 

Let me know if this works. 
Viola

**Comment by violafanfani** [comment]
The LIONESS docs are now explaining how to use the CLI better. Will need to remove --save-memory flag from CLI

**Comment by violafanfani** [comment]
The flag is now removed with #340
