### ISSUE TITLE
Catch gene mismatches in PANDA

### ISSUE THREAD

**Issue by blawney** [netZoo/netZooPy#341]
This isn't so much a bug as an avoidable user error which would be easy to catch/implement. I can submit a PR with a basic patch, if you'd like. 

Further explanation:
We encountered this in JQ's WebMeV project where users upload/explore their own data. Clearly, if one were using the tool directly, they would likely recognize that the symbols in their expression matrix and motif priors don't have any intersection. In our case, someone didn't read the directions carefully and submitted an expression matrix with mouse symbols. Naturally, these symbols did not have any intersection with the symbols contained in the human motif prior matrix (second column). As a result, an error is raised here: https://github.com/netZoo/netZooPy/blob/master/netZooPy/panda/panda.py#L542-L544

(namely, the `idx_genes` array is empty)

The exception was raised by numPy, but the reason was not immediately clear:
```
  File "/opt/conda/lib/python3.10/site-packages/netZooPy/panda/panda.py", line 132, in __init__
    self.processData(
  File "/opt/conda/lib/python3.10/site-packages/netZooPy/panda/panda.py", line 555, in processData
    idx = np.ravel_multi_index(
TypeError: indices must be integral: the provided empty sequence was inferred as float. Wrap it with 'np.array(indices, dtype=np.intp)'
```

So an easy fix here would be to assert a non-zero length of `idx_genes` and `idx_tfs`, raising a clear exception if either is empty.

**Comment by violafanfani** [comment]
Hi @blawney . 
Yes, it all makes a lot of sense, and would be of great help if you could submit a basic path. 
THanks for reporting and helping!
