### ISSUE TITLE
run_lioness.py from command line doesn't work

### ISSUE THREAD

**Issue by twangxxx** [netZoo/netZooPy#35]
Documentation [here ](https://netzoopy.readthedocs.io/en/latest/functions/index.html#run-lioness) mentioned run_lioness.py can be directly run from the command line like `python run_lioness.py -e expression.npy -m motif.npy -p ppi.npy -n panda.npy -o /tmp -f npy 1 100` However, I got this issue suggesting some bugs regarding this usage.

> $ python3 run_lioness.py -e /Users/tian/Documents/GitHub/netZooPy/tests/ToyData/ToyExpressionData.txt
> Traceback (most recent call last):
>   File "run_lioness.py", line 22, in <module>
>     from lioness import Lioness
>   File "/Users/tian/Documents/GitHub/netZooPy/netZooPy/lioness/lioness.py", line 5, in <module>
>     from .timer import Timer
> ImportError: attempted relative import with no known parent package
>

**Comment by marouenbg** [comment]
Yes I am working on this issue since this morning, I will keep you posted.
